import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="AI learning assistant prompt learning plan goal breakdown knowledge explanation analogy layered explanation Socratic questioning active recall spaced repetition error review question generation self-test lecture summary note taking knowledge card learning log review sheet learning road project breakdown code explanation debugging assistance requirement analysis technology selection information retrieval fact-check citation awareness hallucination detection output evaluation rubric checklist template library workflow automation learning AI learning assistant personal knowledge base privacy protection academic integrity compliance cheating risk AI dependence human judgment AI-assisted learning AI tutor intelligent tutoring system adaptive learning personalized learning learning analytics conversational agent dialogue-based tutoring system natural language processing for education educational AI AI ethics responsible AI AI safety prompt engineering prompt patterns prompt templates chain-of-thought tree-of-thought few-shot zero-shot instruction tuning reinforcement learning from human feedback alignment fine-tuning knowledge distillation model compression edge AI on-device AI privacy-preserving AI federated learning synthetic data data augmentation bias detection fairness accountability transparency explainable AI interpretable AI feature importance attention visualization saliency map counterfactual explanation";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"al-tag-"+String(i+1).padStart(3,"0"),name:n,category:"AILearn",description:"AILearn标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"al-course-01",order:1,slug:"AI入门",title:"AI辅助学习入门与边界",description:"AI学习场景、能力边界、伦理安全。",estimatedHours:4,diff:"easy"},
  {id:"al-course-02",order:2,slug:"学习计划",title:"学习计划Prompt与目标拆解",description:"Prompt设计、目标拆解、计划生成。",estimatedHours:8,diff:"easy"},
  {id:"al-course-03",order:3,slug:"知识解释",title:"知识点解释、类比与分层讲解",description:"AI解释、类比、分层、苏格拉底提问。",estimatedHours:8,diff:"medium"},
  {id:"al-course-04",order:4,slug:"题目自测",title:"题目生成、自测与错题复盘",description:"AI出题、自测流程、错题分析。",estimatedHours:8,diff:"medium"},
  {id:"al-course-05",order:5,slug:"笔记总结",title:"笔记整理、知识卡片与总结工作流",description:"AI辅助笔记、总结、知识卡片生成。",estimatedHours:8,diff:"medium"},
  {id:"al-course-06",order:6,slug:"编程辅助",title:"编程学习、代码解释与调试辅助",description:"AI解释代码、调试、优化建议。",estimatedHours:10,diff:"hard"},
  {id:"al-course-07",order:7,slug:"学科场景",title:"英语、数学、计算机基础的AI学习场景",description:"多学科AI辅助学习方法和案例。",estimatedHours:10,diff:"medium"},
  {id:"al-course-08",order:8,slug:"项目辅助",title:"项目学习、需求拆解与技术选型辅助",description:"AI辅助需求分析、方案设计、选型。",estimatedHours:8,diff:"hard"},
  {id:"al-course-09",order:9,slug:"事实核查",title:"资料检索、事实核查与引用意识",description:"AI信息检索、可信度判断、引用。",estimatedHours:8,diff:"hard"},
  {id:"al-course-10",order:10,slug:"工作流模板",title:"AI学习工作流、模板库与自动化",description:"工作流设计、Prompt库、自动化。",estimatedHours:10,diff:"hard"},
  {id:"al-course-11",order:11,slug:"学习日志",title:"学习日志、复盘表与成长档案",description:"AI辅助复盘、日志、档案。",estimatedHours:8,diff:"hard"},
  {id:"al-course-12",order:12,slug:"输出评估",title:"AI输出评估、幻觉识别与质量控制",description:"评估标准、幻觉检测、质量检查。",estimatedHours:8,diff:"hard"},
  {id:"al-course-13",order:13,slug:"安全规范",title:"隐私、安全、学术诚信与使用规范",description:"隐私保护、安全边界、学术诚信、合规。",estimatedHours:8,diff:"hard"},
  {id:"al-course-14",order:14,slug:"AI综合",title:"AI辅助学习综合项目与个人系统搭建",description:"完整AI学习系统、个人助手搭建。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["会用AI辅助学习","能设计Prompt","会评估AI输出","能搭建学习系统"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"al-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["AILearn"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"AIL课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["AI辅助学习","智能学习"],["Prompt工程","提示词"],["知识解释","AI讲解"],["错题复盘","错误分析"],["笔记整理","知识管理"],["编程辅助","代码助手"],["事实核查","信息验证"],["工作流","自动化"],["输出评估","质量检查"],["幻觉识别","错误检测"],["隐私安全","合规"],["学术诚信","规范使用"],["学习日志","复盘"],["模板库","Prompt库"],["学科场景","多学科"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"al-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"AILearn",tags:["AILearn"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"al-kp-"+String(k.length+1).padStart(4,"0"),name:"AIL概念"+(k.length+1),description:"AIL概念",category:"AILearn",tags:["AILearn"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["AI入门","学习计划","知识解释","题目自测","笔记总结","编程辅助","学科场景","项目辅助","事实核查","工作流模板","学习日志","输出评估","安全规范","AI综合"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"AI辅助学习核心？",["主动学习+AI辅助","完全依赖AI","只看AI生成","不思考"],"A","easy"],[1,"Prompt是什么？",["给AI的指令","编程语言","代码工具","数据库"],"A","easy"],[2,"AI解释知识点优点？",["多角度类比","绝对正确","替代老师","替代书本"],"A","medium"],[3,"AI出题要注意？",["事实核查再使用","直接使用","全部接受","不验证"],"A","medium"],[4,"AI辅助笔记作用？",["整理和总结","自动代替","无需人工","无需核对"],"A","medium"],[5,"AI解释代码？",["帮助理解逻辑","自动修改","删除代码","替代测试"],"A","medium"],[6,"AI可能产生？",["幻觉和不准确信息","绝对正确","无错误","完全可靠"],"A","hard"],[7,"使用AI学习底线？",["理解内容后再用","不学习直接问","完全复制","全部依赖"],"A","hard"],[8,"AI输出需评估？",["准确性相关性","美观度","长度","速度"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"al-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:650},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:850},{type:"case_analysis",min:1500}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="al-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于AI学习"+ch+"以下正确的是？",""+ch+"的核心是？","以下哪个不是"+ch+"的内容？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="AI学习"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是AI辅助学习的重要概念。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="AI学习"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在AI辅助学习中的应用。";o=[{label:"A",text:"简答"}];a=ch+"很重要。";}
    else if(it.type==="case_analysis"){s="AI学习"+ch+"案例：设计方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"al-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["高数概念","英语单词","C语言调试","数字逻辑复习","操作系统解释","算法题提示","Java项目拆解","前端组件学习","数据分析报告","RAG项目学习","错题复盘Prompt","学习计划Prompt","知识卡片生成","AI笔记整理","事实核查","幻觉识别","学术诚信","AI依赖修正","个人AI工作流"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"al-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握AI学习",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"场景",description:"分析"},{order:2,title:"Prompt",description:"设计"},{order:3,title:"执行",description:"实施"},{order:4,title:"验证",description:"检查"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"AIL路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"al-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["AI辅助学习","Prompt","知识解释","错题复盘","笔记整理","编程辅助","事实核查","工作流","幻觉","学术诚信","隐私","输出评估","学习日志","模板库","自动化"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["AIL概念"+i,"AIL概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"al-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"AILearn",tags:["AILearn"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["AI学习问题"+(i+1)+"?","AI学习问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"al-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"AILearn",tags:["AILearn"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["AILearn"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["AILearn"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["AILearn"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["AILearn"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["AILearn"]});});return e;}
async function main(){
  console.log("Gen AILearn...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-ai-learning-assistant",slug:"module-ai-learning-assistant",title:"AI辅助学习与自动化学习工作流",subtitle:"面向学生和自学者",description:"面向学生自学者和OpenSkill Galaxy用户的AI辅助学习计划知识解释题目生成错题复盘笔记整理代码学习资料核查工作流模板幻觉识别与合规使用训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["AI学习","Prompt","学习助手","错题复盘","知识管理","自动化学习","事实核查","学习工作流"],estimatedHours:140,difficulty:"beginner",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F916}",repoUrl:"https://github.com/openskill-galaxy/module-ai-learning-assistant",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
